version: "3.7"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost
    volumes:
      - /tmp/app/mysqld:/run/mysqld
