version: "3.7"

services:
  app:
    build: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=15de58ft45efk91yp
      - ALLOWED_HOSTS=127.0.0.0,localhost,pmdsdata12,
      - DEBUG=1
  proxy:
    build: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  static_data:
