version: "3.6"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  adminer_container:
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: 10.4.1.245:6601
      # ADMINER_DESIGN: galkaev
    ports: 
      - 8080:8080
