version: "3.7"

services:
  app:
    build: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=xxxx
      - ALLOWED_HOSTS=127.0.0.0,localhost
  proxy:
    build: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
