version: "3.6"

services:
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - pms:/code
#    ports:
#      - "8000:8000"
    restart: always

  nginx:
    container_name: nginx_proxy
    build: ./nginx
    ports:
      - 80:80
    restart: always
    volumes:
      - pms:/code

volumes:
  pms:
