version: "3.6"

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput  && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"
    restart: always
